from datetime import datetime
from typing import Optional
from sqlalchemy import String,Integer,Float,DateTime,Text,Boolean,ForeignKey,JSON,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from .db import Base
class Vehicle(Base):
 __tablename__='vehicles'; id:Mapped[str]=mapped_column(String(80),primary_key=True); vin:Mapped[Optional[str]]=mapped_column(String(17),unique=True); year:Mapped[Optional[int]]; make:Mapped[Optional[str]]=mapped_column(String(80)); model:Mapped[Optional[str]]=mapped_column(String(80)); trim:Mapped[Optional[str]]=mapped_column(String(80)); mileage:Mapped[Optional[int]]; metadata_json:Mapped[dict]=mapped_column(JSON,default=dict)
class Source(Base):
 __tablename__='sources'; id:Mapped[int]=mapped_column(primary_key=True,autoincrement=True); title:Mapped[str]=mapped_column(String(300)); source_type:Mapped[str]=mapped_column(String(40)); authority_rank:Mapped[int]; url:Mapped[Optional[str]]=mapped_column(Text); accessed_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); notes:Mapped[Optional[str]]=mapped_column(Text)
class DiagnosticSession(Base):
 __tablename__='diagnostic_sessions'; id:Mapped[str]=mapped_column(String(64),primary_key=True); vehicle_id:Mapped[str]=mapped_column(ForeignKey('vehicles.id')); source_format:Mapped[str]=mapped_column(String(40)); source_name:Mapped[str]=mapped_column(String(260)); sha256:Mapped[str]=mapped_column(String(64),index=True); started_at:Mapped[Optional[datetime]]; ended_at:Mapped[Optional[datetime]]; mileage:Mapped[Optional[int]]; timezone:Mapped[Optional[str]]=mapped_column(String(80)); parser_version:Mapped[str]=mapped_column(String(40),default='0.1'); warnings:Mapped[list]=mapped_column(JSON,default=list); raw_path:Mapped[str]=mapped_column(Text); normalized_path:Mapped[str]=mapped_column(Text); __table_args__=(UniqueConstraint('vehicle_id','sha256',name='uq_session_vehicle_hash'),)
class DTC(Base):
 __tablename__='dtcs'; id:Mapped[int]=mapped_column(primary_key=True,autoincrement=True); session_id:Mapped[str]=mapped_column(ForeignKey('diagnostic_sessions.id'),index=True); module:Mapped[Optional[str]]=mapped_column(String(40)); code:Mapped[str]=mapped_column(String(16),index=True); status:Mapped[Optional[str]]=mapped_column(String(80)); description:Mapped[Optional[str]]=mapped_column(Text); freeze_frame:Mapped[dict]=mapped_column(JSON,default=dict)
class Measurement(Base):
 __tablename__='measurements'; id:Mapped[int]=mapped_column(primary_key=True,autoincrement=True); session_id:Mapped[str]=mapped_column(ForeignKey('diagnostic_sessions.id'),index=True); ts:Mapped[Optional[datetime]]=mapped_column(DateTime,index=True); module:Mapped[Optional[str]]=mapped_column(String(40)); name:Mapped[str]=mapped_column(String(120),index=True); value_num:Mapped[Optional[float]]; value_text:Mapped[Optional[str]]=mapped_column(Text); unit:Mapped[Optional[str]]=mapped_column(String(40)); raw:Mapped[dict]=mapped_column(JSON,default=dict)
class CANFrame(Base):
 __tablename__='can_frames'; id:Mapped[int]=mapped_column(primary_key=True,autoincrement=True); session_id:Mapped[str]=mapped_column(ForeignKey('diagnostic_sessions.id'),index=True); ts_epoch:Mapped[Optional[float]]=mapped_column(Float,index=True); interface:Mapped[Optional[str]]=mapped_column(String(40)); arbitration_id:Mapped[int]=mapped_column(Integer,index=True); is_extended:Mapped[bool]=mapped_column(Boolean,default=False); dlc:Mapped[int]; data_hex:Mapped[str]=mapped_column(String(128)); decoded:Mapped[dict]=mapped_column(JSON,default=dict)
class MaintenanceRecord(Base):
 __tablename__='maintenance_records'; id:Mapped[int]=mapped_column(primary_key=True,autoincrement=True); vehicle_id:Mapped[str]=mapped_column(ForeignKey('vehicles.id'),index=True); service_key:Mapped[str]=mapped_column(String(100),index=True); performed_at:Mapped[Optional[datetime]]; mileage:Mapped[Optional[int]]; record_type:Mapped[str]=mapped_column(String(40)); status:Mapped[str]=mapped_column(String(40),default='completed'); notes:Mapped[Optional[str]]=mapped_column(Text); evidence:Mapped[list]=mapped_column(JSON,default=list)
class PartOption(Base):
 __tablename__='part_options'; id:Mapped[int]=mapped_column(primary_key=True,autoincrement=True); vehicle_id:Mapped[str]=mapped_column(ForeignKey('vehicles.id'),index=True); system:Mapped[str]=mapped_column(String(80),index=True); slot:Mapped[str]=mapped_column(String(120),index=True); tier:Mapped[str]=mapped_column(String(40)); manufacturer:Mapped[Optional[str]]=mapped_column(String(100)); part_number:Mapped[Optional[str]]=mapped_column(String(100)); name:Mapped[str]=mapped_column(String(240)); fitment_status:Mapped[str]=mapped_column(String(40),default='unverified'); evidence:Mapped[list]=mapped_column(JSON,default=list); notes:Mapped[Optional[str]]=mapped_column(Text)
