"""Export/sync bridge — make Postgres the source, markdown/JSON the artifacts.

`build_snapshot()` assembles one dict of the whole car (vehicle, specs, mods,
issues, maintenance-due, cost rollups, sources). From it:
  - `render_mods_md()` produces a MODS.md the PWA references,
  - `garage.json` gives the dashboard a single feed to read instead of inline data.

This closes the drift between the database and the markdown surfaces: approved
facts flow out; nothing here writes back to the DB.
"""
from __future__ import annotations

import datetime as dt
import json
from decimal import Decimal
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.orm import Session

from . import service
from .models import Issue, Mod, OdometerReading, Part, ServiceEvent, Source, Spec


def _f(v) -> float | None:
    return float(v) if isinstance(v, (Decimal, int, float)) else None


def build_snapshot(session: Session, vehicle_id: int,
                   current_miles: int | None = None) -> dict:
    from .models import Vehicle
    veh = session.get(Vehicle, vehicle_id)

    # Fall back to the latest odometer reading when no mileage was supplied.
    if current_miles is None:
        latest = session.scalar(
            select(OdometerReading).where(OdometerReading.vehicle_id == vehicle_id)
            .order_by(OdometerReading.recorded_at.desc(), OdometerReading.id.desc())
        )
        current_miles = latest.miles if latest else None

    specs = session.scalars(
        select(Spec).where(Spec.vehicle_id == vehicle_id).order_by(Spec.category, Spec.name)
    ).all()
    mods = session.scalars(select(Mod).where(Mod.vehicle_id == vehicle_id).order_by(Mod.slot)).all()
    issues = session.scalars(
        select(Issue).where(Issue.vehicle_id == vehicle_id).order_by(Issue.opened_at.desc())
    ).all()
    services = session.scalars(
        select(ServiceEvent).where(ServiceEvent.vehicle_id == vehicle_id)
        .order_by(ServiceEvent.performed_at.desc())
    ).all()
    parts = session.scalars(select(Part).where(Part.vehicle_id == vehicle_id)).all()
    sources = session.scalars(select(Source).order_by(Source.authority)).all()

    # cost rollups
    mod_cost = sum(_f(m.cost) or 0 for m in mods)
    service_cost = sum(_f(s.cost) or 0 for s in services)
    parts_cost = sum(_f(p.approx_price) or 0 for p in parts)
    by_category: dict[str, float] = {}
    for m in mods:
        by_category[m.stage or "unstaged"] = by_category.get(m.stage or "unstaged", 0) + (_f(m.cost) or 0)

    return {
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "current_miles": current_miles,
        "vehicle": {
            "vin": veh.vin, "year": veh.year, "make": veh.make, "model": veh.model,
            "trim": veh.trim, "engine": veh.engine, "transmission": veh.transmission,
            "notes": veh.notes,
        },
        "specs": [{"category": s.category, "name": s.name, "value": s.value,
                   "unit": s.unit, "verification": s.verification} for s in specs],
        "mods": [{"slot": m.slot, "part_name": m.part_name, "part_number": m.part_number,
                  "stage": m.stage, "cost": _f(m.cost), "url": m.url,
                  "installed_on": m.installed_on.isoformat() if m.installed_on else None,
                  "installed_miles": m.installed_miles, "verification": m.verification}
                 for m in mods],
        "issues": [{"title": i.title, "status": i.status, "severity": i.severity,
                    "root_cause": i.root_cause, "verification": i.verification,
                    "opened_at": i.opened_at.isoformat() if i.opened_at else None}
                   for i in issues],
        "service_history": [{"item": s.item, "performed_at": s.performed_at.isoformat(),
                             "miles": s.miles, "cost": _f(s.cost), "vendor": s.vendor}
                            for s in services],
        "maintenance_due": service.due_list(session, vehicle_id, current_miles=current_miles),
        "recalls": service.list_recalls(session, vehicle_id),
        "costs": {"mods": round(mod_cost, 2), "service": round(service_cost, 2),
                  "parts": round(parts_cost, 2),
                  "total": round(mod_cost + service_cost + parts_cost, 2),
                  "by_stage": {k: round(val, 2) for k, val in by_category.items()}},
        "sources": [{"name": s.name, "authority": s.authority, "kind": s.kind} for s in sources],
    }


_COND = {"VEHICLE_VERIFIED": "✅", "OEM_VERIFIED": "✅", "CORROBORATED": "🔧", "UNVERIFIED": "⚠️"}


def render_mods_md(snap: dict) -> str:
    """Render a MODS.md from the snapshot. Auto-generated — matches the PWA's
    convention (the app treats MODS.md as generated, never hand-edited)."""
    veh = snap["vehicle"]
    lines = [
        f"# MODS — {veh['year']} {veh['make']} {veh['model']} {veh['trim']}",
        "",
        f"> Auto-generated by digital-garage on {snap['generated_at'][:10]} — do not hand-edit.",
        f"> VIN {veh['vin']} · {veh['engine']} · {veh['transmission']}",
        "",
    ]
    mods = snap["mods"]
    if not mods:
        lines += ["_No modifications recorded — vehicle at stock baseline._", ""]
    else:
        lines += ["| Slot | Part | Stage | Installed | Cost | Evidence |",
                  "|------|------|-------|-----------|------|----------|"]
        for m in mods:
            cond = _COND.get(m["verification"], "⚠️")
            part = f"[{m['part_name']}]({m['url']})" if m.get("url") else m["part_name"]
            cost = f"${m['cost']:,.2f}" if m.get("cost") is not None else "—"
            when = m.get("installed_on") or "—"
            lines.append(f"| {m['slot']} | {part} | {m.get('stage') or '—'} | {when} | {cost} | {cond} {m['verification']} |")
        lines.append("")

    c = snap["costs"]
    lines += ["## Spend", "",
              f"- Mods: **${c['mods']:,.2f}**",
              f"- Parts (purchased): **${c['parts']:,.2f}**",
              f"- Service: **${c['service']:,.2f}**",
              f"- **Total: ${c['total']:,.2f}**", ""]

    due = [d for d in snap["maintenance_due"] if d["status"] in ("overdue", "due-soon")]
    if due:
        lines += ["## Maintenance attention", ""]
        for d in due:
            flag = "🔴" if d["status"] == "overdue" else "🟡"
            lines.append(f"- {flag} **{d['item']}** — {d['status']} ({d['detail']})")
        lines.append("")
    return "\n".join(lines)


def write_export(session: Session, vehicle_id: int, *, current_miles: int | None = None,
                 repo_root: Path | None = None, json_dir: Path | None = None) -> dict:
    """Write MODS.md (repo root) and garage.json (data/export/). Returns paths."""
    snap = build_snapshot(session, vehicle_id, current_miles=current_miles)
    repo_root = repo_root or Path(__file__).resolve().parent.parent.parent  # focus-st/
    # garage.json lives beside the dashboard in web/ (garage.html fetches
    # ./garage.json); the human-readable MODS.md lives with the data in data/.
    json_dir = json_dir or (repo_root / "web")
    json_dir.mkdir(parents=True, exist_ok=True)
    data_dir = repo_root / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    mods_md_path = data_dir / "MODS.md"
    garage_json_path = json_dir / "garage.json"
    mods_md_path.write_text(render_mods_md(snap))
    garage_json_path.write_text(json.dumps(snap, indent=2))
    return {"mods_md": str(mods_md_path), "garage_json": str(garage_json_path),
            "mods": len(snap["mods"]), "total_cost": snap["costs"]["total"]}
