"""FEED — per-machine garage.json feed + MODS.md for the fleet.

The Focus ST's `garage.json` + `MODS.md` come from the V1 export (real mods/service). The
four fleet machines have no V1 mod/service records, but they *do* have a commissioned
digital twin — so their honest "changes / unknowns from stock" is the twin's
reference-vs-actual deviations. This projects that into:

  • `data/vehicles/<slug>/MODS.md`   — the deviations, as the `fleet.json` `mods` path expects
  • `web/vehicles/<slug>/garage.json` — a compact feed (reference header + deviations)

Read-only, regenerated from canon. Flagship focus-st is excluded — it has its richer V1
export. `intel.json` remains the full projection; this is the lightweight feed alongside it.
"""
from __future__ import annotations

import datetime as dt
import json
from pathlib import Path

from sqlalchemy.orm import Session

REPO = Path(__file__).resolve().parent.parent.parent
FLEET = ("zzr600", "rz350", "tz250", "toyota-pickup")

_COND_ICON = {"failed": "🔴", "modified": "🟡", "removed": "⚫", "suspect": "⚠️", "worn": "🟠"}


def render_fleet_mods(header: dict | None, slug: str, deviations: list[dict],
                      *, today: dt.date | None = None) -> str:
    """Render a MODS.md from the twin's deviations-from-stock. Pure."""
    name = (header or {}).get("name") or slug
    stamp = (today or dt.date.today()).isoformat()
    lines = [f"# MODS — {name}", "",
             f"> Auto-generated by digital-garage on {stamp} — do not hand-edit.",
             "> Changes & unknowns vs stock, projected from the digital twin "
             "(this machine has no logged V1 mods yet).", ""]
    if not deviations:
        lines.append("_No recorded deviations from stock — the twin matches the reference._")
        return "\n".join(lines) + "\n"
    lines += ["| Component | State | Installed | Knowledge |",
              "|-----------|-------|-----------|-----------|"]
    for d in deviations:
        icon = _COND_ICON.get(d.get("condition"), "·")
        lines.append(f"| {d.get('slug', '?')} | {icon} {d.get('condition', '?')} "
                     f"| {d.get('installed_part') or '—'} | {d.get('knowledge_state') or '—'} |")
    return "\n".join(lines) + "\n"


def build_fleet_feed(session: Session, slug: str) -> dict:
    """A compact garage.json feed for a fleet machine: reference header + twin deviations.
    The full projection stays in intel.json — this is the lightweight sibling."""
    from . import refservice, twin
    header = refservice.variant_header(session, slug)
    rva = twin.reference_vs_actual(session, slug)
    deviations = rva["deviations"] if rva else []
    return {
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "variant": slug,
        "reference": header,
        "changes_from_stock": deviations,
        "source": "digital-garage twin projection",
        "full_intelligence": "intel.json",
    }


def write_fleet_feed(session: Session, slug: str) -> dict:
    """Write MODS.md + garage.json for one fleet machine. Returns the paths."""
    from . import refservice
    header = refservice.variant_header(session, slug)
    feed = build_fleet_feed(session, slug)
    mods_md = render_fleet_mods(header, slug, feed["changes_from_stock"])

    mods_path = REPO / "data" / "vehicles" / slug / "MODS.md"
    feed_path = REPO / "web" / "vehicles" / slug / "garage.json"
    mods_path.parent.mkdir(parents=True, exist_ok=True)
    feed_path.parent.mkdir(parents=True, exist_ok=True)
    mods_path.write_text(mods_md)
    feed_path.write_text(json.dumps(feed, indent=2))
    return {"mods_md": str(mods_path), "garage_json": str(feed_path),
            "changes": len(feed["changes_from_stock"])}


def write_fleet_feed_all(session: Session, slugs: tuple[str, ...] = FLEET) -> list[dict]:
    from . import refservice
    return [write_fleet_feed(session, s) for s in slugs
            if refservice.variant_header(session, s) is not None]
